#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Nov 13 17:18:29 +03 2024
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 1392c362dc914ad9a31a9d78b3b1c774 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot TB_sev_seg_decoder_behav xil_defaultlib.TB_sev_seg_decoder xil_defaultlib.glbl -log elaborate.log"
xelab -wto 1392c362dc914ad9a31a9d78b3b1c774 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot TB_sev_seg_decoder_behav xil_defaultlib.TB_sev_seg_decoder xil_defaultlib.glbl -log elaborate.log

